### PR TITLE
Sovd on windows

### LINKED ISSUE #12: [Bug] <short summary>
## Description
EntityCollectionEntityIdDataDataIdGetResponse denfintion missing
use openapi_client::EntityCollectionEntityIdDataDataIdGetResponse;
use openapi_client::EntityCollectionEntityIdDataGetResponse;
use openapi_client::EntityCollectionEntityIdDataGroupsGetResponse;
use openapi_client::EntityCollectionEntityIdGetResponse;
However, these types are not found in the openapi_client crate.
The only available types I can see in the generated library (lib.rs) are:

V1ComponentsEntityIdDataDataIdGetResponse, and

EntityIdDataDataIdGet200Response.

It seems the OpenAPI code generator used the prefix V1Components... for all endpoint response enums (based on the path /v1/components/...), so the expected symbols like EntityCollectionEntityIdDataDataIdGetResponse don’t exist under those names.

In the sovd-handler module, I’m trying to call the following imports from the OpenAPI client:

## Steps to Reproduce

1. Step 1
2. Step n

## Actual Behavior

What actually happened when you followed the steps above?

## Screenshots or Logs (if applicable)

Add logs, screenshots, or crash traces that help explain the problem.

## Environment

- OS: [e.g. Ubuntu 22.04, Windows 11]
- Version: [e.g. v0.2.1, main]

## Additional Context

> [!IMPORTANT]
> Link the pull request that addresses this bug once created.

### PR DESCRIPTION
**Pull request by ulrichrenner**
## Summary

I adapted mainly sovd handler code and project manifest files with the aim to be able to compile the project utilizing toolchains 

- stable-x86_64-pc-windows-msvc
- stable-x86_64-pc-windows-gnu

To setup the project on windows hosts, batch file build.cmd (clone of build.sh) is introduced.

## Checklist

- [x] I have tested my changes locally
- [x] I have added or updated documentation
- [ ] I have linked related issues or discussions
- [x] I have added or updated tests

### CODE REVIEW

File: sovd-server/src/sovd_server.rs [hunk 1]
```diff
@@ -1,2088 +1,2679 @@
...
+use crate::server_config::ServiceDaemonWrapper;
+
+// Import the required modules
+use sovd_handlers::IDENT_DATA_RESPONSE;
+use sovd_handlers::create_entity_collection_response;
+use sovd_handlers::filter_by_writable;
+use sovd_handlers::find_and_create_read_value;
+use sovd_handlers::find_processes;
+use sovd_handlers::find_single_process;
+use sovd_handlers::get_before_last_dash;
```
Comment (rama492) [inline sovd-server/src/sovd_server.rs]: seems like this isnt used in code. we can remove this and also from lib.rs?
